exclude: "pytest/.*/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Simply check whether files parse as valid python
      - id: check-ast
      # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything
      - id: check-symlinks
      # Attempts to load all TOML files to verify syntax
      - id: check-toml
      # Attempts to load all YAML files to verify syntax
      - id: check-yaml
      # Check for calls to breakpoint()
      - id: debug-statements
      # Makes sure files end in a newline and only a newline
      - id: end-of-file-fixer
      # Disallow commiting directly to "master"
      - id: no-commit-to-branch
      # Check the kind of line ending (LF or CRLF)
      - id: mixed-line-ending
      # Trim trailing whitespaces
      - id: trailing-whitespace

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: "v0.0.291"
  #   hooks:
  #     - id: ruff

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.5"
    hooks:
      - id: codespell
        args: ["-L", "ba,informations,inout,ist,lamda,ment,noe,periode,sur", "--skip", "capytaine/green_functions/libDelhommeau/src/old_Prony_decomposition.f90"]
